# Generated by Django 2.1.1 on 2018-09-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userlist',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('type', models.IntegerField()),
                ('state', models.IntegerField()),
            ],
            options={
                'db_table': 'userlist',
            },
        ),
    ]
