# Generated by Django 2.1.1 on 2018-09-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='test2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=100)),
                ('y', models.IntegerField()),
            ],
            options={
                'db_table': 'test2',
            },
        ),
    ]
