# Generated by Django 2.1.1 on 2018-09-05 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0004_auto_20180905_1109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userlist',
        ),
    ]
