# Generated by Django 2.1.1 on 2018-09-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0005_delete_userlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('type', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'userlist',
            },
        ),
    ]
