# Generated by Django 2.1.1 on 2018-09-05 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0006_auto_20180905_1119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test2',
        ),
    ]
