# Generated by Django 2.1.1 on 2018-09-05 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0008_tbsecadjcell'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbsecadjcell',
            options={'managed': False},
        ),
    ]
