# Generated by Django 2.1.1 on 2018-09-05 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Log', '0009_auto_20180905_1524'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userinfo',
        ),
    ]
